name: Build-Windows

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      # https://github.com/marketplace/actions/ccache-for-gh-actions
      - name: Ccache for gh actions
        uses: hendrikmuhs/ccache-action@v1.2.8

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements.txt
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Standalone build with nuitka
        run: python -m nuitka --standalone --assume-yes-for-downloads --include-package=kivy --include-data-files=kv_main.kv=kv_main.kv --include-data-dir=uix=kivymd/uix --include-data-dir=data=kivymd/data --noinclude-unittest-mode=nofollow --jobs=4 main.py

      - name: Upload standalone build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build Standalone
          path: |
            main.dist/
